### ISSUE TITLE
preparing the input

### ISSUE THREAD

**Issue by ilaydagulmez** [almeidasilvaf/doubletrouble#1] opened 2024-03-12 06:36 UTC
Hi, 
I am having trouble with the input file format and despite following the tutorials you provided, the output file remains empty like this:
<img width="1119" alt="Ekran Resmi 2024-03-11 16 15 13" src="https://github.com/almeidasilvaf/doubletrouble/assets/163100594/4e7ab734-372c-4f2a-a09e-8134e40fb020">

This file is a protein fasta file like this:
<img width="729" alt="Ekran Resmi 2024-03-12 09 34 31" src="https://github.com/almeidasilvaf/doubletrouble/assets/163100594/15d4484c-f409-4847-a108-35acc1f6bf04">

I have tried this command aa=fasta2AAStringSetlist("XXX.aa.fasta") for the AAString format but as I said there is an empty file for the result. 

Do you have any suggestions to help me resolve this issue? Thank you for your time and this great tool.

Best regards.

**Comment by almeidasilvaf** [comment] 2024-03-12 07:30
Hi, @ilaydagulmez 

Thank you for using __doubletrouble__. ;-)

I see where the problem is. The function `fasta2AAStringSetlist()` takes as input the path to a *directory* containing one or multiple FASTA files, each of which will be read an `AAStringSet` object and stored in elements of a list. In your example, you're using as input the path to a *FASTA file*, not *a directory of FASTA files*. This is described in the help page of the function (which can be accessed with `?syntenet::fasta2AAStringSetlist`). It's always good to read the help pages of functions first to be sure of what to use as input to each parameter. 

Let's suppose your FASTA file *XXX.aa.fasta* is in `myproject/data`. Then, you'd use:

```r
aa <- fasta2AAStringSetlist("myproject/data")
``` 

Anyway, I will update this function (which is part of {syntenet}) to return an error when users input path to files. You should get an error, not an empty list.

Could you try using the path to the directory (instead of the file) and let me know if it works well for you?

Best,
Fabricio

**Comment by ilaydagulmez** [comment] 2024-03-12 07:50
Hi Fabricio,

Thanks for your help, it works! Now I'm gonna try run DIAMOND and prepare inputs data. 

Thanks again,

Best regards

**Comment by almeidasilvaf** [comment] 2024-03-12 07:56
Great to hear it! 

I'll close this issue, then. Feel free to open other issues if you happen to find any bug or if something does not work as expected.

Best,
Fabricio

**Closed as completed by almeidasilvaf** 2024-03-12 07:56 UTC
